### ISSUE TITLE
Octane swoole initialization error - Fatal error: Uncaught ReflectionException: Class "config" does not exist in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:959

### ISSUE THREAD

**Issue by IbrahimHastorun** [laravel/octane#1045]
### Octane Version

2.11

### Laravel Version

11.31

### PHP Version

8.2

### What server type are you using?

Swoole

### Server Version

Ubuntu 24.04 (Noble Numbat)

### Database Driver & Version

Docker images postgres :15-alpine

### Description

I get an error when starting my project even though I haven't changed anything in my project, I turned my project into docker images and ran it but I got an error, I stand up my project with octane swoole, I got the same error in version 2.6, I switched to version 2.11 but I still get the same error, please solve my problem.

### Steps To Reproduce

Error:  Fatal error: Uncaught ReflectionException: Class "config" does not exist in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:959
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(959): ReflectionClass->__construct('config')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(832): Illuminate\Container\Container->build('config')
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(763): Illuminate\Container\Container->resolve('config', Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(124): Illuminate\Container\Container->make('config', Array)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(279): app('config')
#5 /var/www/html/vendor/laravel/octane/src/Swoole/Handlers/OnWorkerStart.php(119): config('octane.swoole.c...', true)
#6 /var/www/html/vendor/laravel/octane/src/Swoole/Handlers/OnWorkerStart.php(33): Laravel\Octane\Swoole\Handlers\OnWorkerStart->shouldClearOpcodeCache()
#7 /var/www/html/vendor/laravel/octane/bin/swoole-server(97): Laravel\Octane\Swoole\Handlers\OnWorkerStart->__invoke(Object(Swoole\Http\Server), 2)
#8 /var/www/html/vendor/laravel/octane/bin/swoole-server(97): {closure}('/var/www/html')
#9 [internal function]: {closure}(Object(Swoole\Http\Server), 2)
#10 /var/www/html/vendor/laravel/octane/bin/swoole-server(172): Swoole\Server->start()

**Comment by pedrovian4** [comment]
Getting this error right now also

**Comment by lumamontes** [comment]
i'm also getting this error right now

**Comment by georgefromohio** [comment]
Voting this up same issue! Have to 
```
# Pin to 2.11.0
"laravel/octane": "2.11.0",  # in composer
# Update
> composer update laravel/octane --with-dependencies
# Clear all config caches
> php artisan config:clear && ...
```
For anything to begin working again

**Comment by Lorenalgm** [comment]
Same here :((

**Comment by georgefromohio** [comment]
Didn't mean to propagate this, apparently this has been resolved but not bumped [[see 1037](https://github.com/laravel/octane/pull/1037)]. The fix for now with 2.12 is adding this to your `config/octane.php`
```php
'swoole' => [
        'clear_opcache' => false,
        'options' => [
            'compression_min_length' => 20,
        ...
```

**Comment by pedrovian4** [comment]
> Didn't mean to propagate this, apparently this has been resolved but not bumped [[see 1037](https://github.com/laravel/octane/pull/1037)]. The fix for now with 2.12 is adding this to your `config/octane.php`
> ```php
> 'swoole' => [
>         'clear_opcache' => false,
>         'options' => [
>             'compression_min_length' => 20,
>         ...
> ```

Did not work, i just migrate to franken php

**Comment by sy-records** [comment]
> The fix for now with 2.12 is adding this to your `config/octane.php`
> ```php
> 'swoole' => [
>         'clear_opcache' => false,
>         'options' => [
>             'compression_min_length' => 20,
>         ...
> ```

This is just a way to disable cleaning opcache, not a way to fix the problem.

Since the new version has not been released, we can only go back to 2.11.0 or use 2.x-dev.

**Comment by IbrahimHastorun** [comment]
> > Şimdilik 2.12'deki düzeltme şunu eklemektir:`config/octane.php`
> > 'swoole' => [
> >         'clear_opcache' => false,
> >         'options' => [
> >             'compression_min_length' => 20,
> >         ...
> 
> Bu, opcache temizlemeyi devre dışı bırakmanın bir yoludur, sorunu çözmenin bir yolu değildir.
> 
> Yeni sürüm henüz yayınlanmadığı için sadece 2.11.0'a geri dönebiliriz veya 2.x-dev'i kullanabiliriz.

I got the error in version 2.11, it was already in version 2.6 at first, then I made it 2.11, but the error is still the same, it's funny that such an important package in the laravel's ecosystem gives an error.

**Comment by sy-records** [comment]
It was introduced in version 2.12. If you appear in 2.11, it may be your installation error. The installation is 2.12.

**Comment by IbrahimHastorun** [comment]
> It was introduced in version 2.12. If you appear in 2.11, it may be your installation error. The installation is 2.12.

Is 2.12 the version giving the error? 2 weeks ago when I published the project with the same codes in version 2.6 there was no error, but yesterday I got an error, the codes are the same, the environment is the same, ubuntu vps docker

**Comment by rahimi-ali** [comment]
just to provide some more information:

PHP version: 8.4.7
Swoole version: 6.0.2
Laravel version: 12.21.0

Having the same issue with version 2.12 of octane but everything is fine in version 2.11 with the same environment.

**Comment by IbrahimHastorun** [comment]
> just to provide some more information:
> 
> PHP version: 8.4.7 Swoole version: 6.0.2 Laravel version: 12.21.0
> 
> Having the same issue with version 2.12 of octane but everything is fine in version 2.11 with the same environment.

Can you share composer.json and DockerFile files

**Comment by 4H1R** [comment]
Any updates on this Issue? We still have this issue even tho we've added 

```php
'clear_opcache' => false,
```

**Comment by pilutiful** [comment]
I'm experiencing the same problem. Fresh install of Laravel 12.21.0 with Octane swoole, getting error:

PHP Fatal error:  Uncaught ReflectionException: Class "config" does not exist in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:1043       

As a side note, I'm using Laravel Sail

**Comment by kaioken** [comment]
@pilutiful use `"laravel/octane": "^2.x-dev",` or downgrade until they make the release

**Comment by IbrahimHastorun** [comment]
> [@pilutiful](https://github.com/pilutiful) use `"laravel/octane": "^2.x-dev",` or downgrade until they make the release

Can you share the composer.json and DockerFile files, if any, I need to solve this problem urgently.

**Comment by 4H1R** [comment]
> Can you share the composer.json and DockerFile files, if any, I need to solve this problem urgently.

We've used the octane version 2.11 ( basically remove the ^ from any version you're using ) and it's working for us

And for docker file in production we're inspired by https://github.com/exaco/laravel-octane-dockerfile

**Comment by jack20211101** [comment]
I also encountered the same problem port startup, http error 500

**Comment by rcerljenko** [comment]
Same problem

**Comment by GigaFyde** [comment]
Oh, so its upstream. been losing my mind for the past few hours trying to find where in my code the issue was.

**Comment by georgefromohio** [comment]
> Didn't mean to propagate this, apparently this has been resolved but not bumped [[see 1037](https://github.com/laravel/octane/pull/1037)]. The fix for now with 2.12 is adding this to your `config/octane.php`
> 
> 'swoole' => [
>         'clear_opcache' => false,
>         'options' => [
>             'compression_min_length' => 20,
>         ...

Sorry for the confusion this has caused. What has worked for me is what I previously suggested. Which everyone else echoed. Pin the version to 2.11 and make sure you you downgrade with dependencies, (and ofc clear all your cache, restart your workers)

**Comment by mattpannella** [comment]
same issue here. i pinned octane 2.11 and it fixedt he issue

**Comment by IbrahimHastorun** [comment]
For friends who have the same problem, when the package is defined like this in composer.json, it gives no error
"laravel/octane": "2.11"
you can use it this way
I hope this error will be solved for new versions as soon as possible

**Comment by XuPaoYe** [comment]
/vendor/laravel/octane/bin/swoole-server on line 147

Fatal error: Uncaught Error: Call to a member function handleTick() on null in

**Comment by mrfade** [comment]
downgrading to 2.11 fixes the issue. however, the issue is fixed in #1037 but has not released yet.

**Comment by crynobone** [comment]
Fixed via https://github.com/laravel/octane/pull/1037 and pending a release.
